version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ntlp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: conf
      POSTGRES_USER: ntlp_user
      POSTGRES_PASSWORD: ${DB_PASS:-ntlp_secure_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - ntlp-network

  # NTLP Backend API
  backend:
    build: .
    container_name: ntlp-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: conf
      DB_USER: ntlp_user
      DB_PASS: ${DB_PASS:-ntlp_secure_pass}
      JWT_SECRET: ${JWT_SECRET:-your-super-secure-jwt-secret}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - ntlp-network
    volumes:
      - ./logs:/app/logs

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: ntlp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - ntlp-network

volumes:
  postgres_data:

networks:
  ntlp-network:
    driver: bridge
